<h2>Iniciar Sesi&oacute;n</h2>

<form name="form1" method="post" action="">
    <input type="hidden" value="1" name="enviar" />
     <p>
        <label>Ci: </label>
        <input type="text" name="ci" value="<?php if(isset($this->datos)) echo $this->datos['ci']; ?>"/>
    </p>
     <p>
        <label>Nombre: </label>
        <input type="text" name="nombre" value="<?php if(isset($this->datos)) echo $this->datos['nombre']; ?>"/>
    </p>
    <p>
        <label>Usuario: </label>
        <input type="text" name="usuario" value="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>"/>
    </p>
    <p>
        <label>Email: </label>
        <input type="text" name="email" value="<?php if(isset($this->datos)) echo $this->datos['email']; ?>"/>
    </p>
    <p>
        <label>Telefono: </label>
        <input type="text" name="telefono" value="<?php if(isset($this->datos)) echo $this->datos['telefono']; ?>"/>
    </p>
     <p>
        <label>Password: </label>
        <input type="password" name="password" />
    </p>
    <p>
        <label>Confirmar: </label>
        <input type="password" name="confirmar" />
    </p>
     
     <p>
        <label></label>
        <input type="submit" value="enviar" />
    </p>
</form>
