<h2>vista hola</h2>

<?php 
if(isset($this->posts) && count($this->posts)): ?>
    <table>
    <?php for($i = 0; $i <count($this->posts); $i++): ?>
        <tr>
            <?php //nombre de los campos de la tabla ?>
            <td><?php echo $this->posts[$i]['codigo']; ?></td>
            <td><?php echo $this->posts[$i]['nombre']; ?></td>
            <td><?php echo $this->posts[$i]['precio']; ?></td>


            
        </tr>
 <?php endfor; ?>   
    </table>
<?php else: ?>
<p><strong>No hay nadie</string></p>
<?php endif; ?>